# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "php-composer-deploy"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Lombardo"]
  s.date = "2013-07-25"
  s.description = "Replacement for the rails deploy strategy which ships with Capistrano, allows you to deploy php composer projects with ease."
  s.email = "me@joseph-lombardo.com"
  s.extra_rdoc_files = [
    "LICENSE.markdown",
    "README.markdown"
  ]
  s.files = [
    "CHANGELOG.markdown",
    "LICENSE.markdown",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/php-composer-deploy.rb",
    "php-composer-deploy.gemspec"
  ]
  s.homepage = "http://github.com/lombardoja/php-composer-deploy/"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Replacement for the default Capistrano tasks, designed to make life easier for PHP devs using composer"
end

